# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: git pull origin master
    - name: Afficher le contenu du répertoire de travail
      run: |
          ls -la
      working-directory: /express
    - run: cat index.js
      working-directory: /express
    - run: npm i
      working-directory: /express
    - run: pm2 restart index
      working-directory: /express
